# Generated by Django 3.0 on 2019-12-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='insert_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('insert_date', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Complaint')),
            ],
        ),
    ]
